# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'Movies' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # ignore all warnings from all pods
  inhibit_all_warnings!

  # Pods for Movies
  pod 'Alamofire', '~> 4.7'

end
